### ISSUE TITLE
Permission issue from image picker

### ISSUE THREAD

**Issue by bitfriend** [effektio/effektio#263]
I am getting error on image picker in chat room.
```
E/AndroidRuntime(13185): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2346, result=-1, data=Intent { dat=content://media/external/images/media/39 }} to activity {org.effektio.app/com.example.effektio.MainActivity}: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/39 from pid=13185, uid=10061 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
E/AndroidRuntime(13185): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
E/AndroidRuntime(13185): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
E/AndroidRuntime(13185): 	at android.app.ActivityThread.-wrap16(ActivityThread.java)
E/AndroidRuntime(13185): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
E/AndroidRuntime(13185): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(13185): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(13185): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/AndroidRuntime(13185): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13185): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime(13185): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/AndroidRuntime(13185): Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/39 from pid=13185, uid=10061 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
E/AndroidRuntime(13185): 	at android.os.Parcel.readException(Parcel.java:1599)
E/AndroidRuntime(13185): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
E/AndroidRuntime(13185): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
E/AndroidRuntime(13185): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
E/AndroidRuntime(13185): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1104)
E/AndroidRuntime(13185): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
E/AndroidRuntime(13185): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
E/AndroidRuntime(13185): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:45)
E/AndroidRuntime(13185): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseMultiImageResult(ImagePickerDelegate.java:504)
E/AndroidRuntime(13185): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:467)
E/AndroidRuntime(13185): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
E/AndroidRuntime(13185): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
E/AndroidRuntime(13185): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
E/AndroidRuntime(13185): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
E/AndroidRuntime(13185): 	at android.app.Activity.dispatchActivityResult(Activity.java:6428)
E/AndroidRuntime(13185): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
E/AndroidRuntime(13185): 	... 9 more
I/Process (13185): Sending signal. PID: 13185 SIG: 9
```
My env is android api 23 emulator.
I guess `permission_handler` is not working well.

**Comment by sachintha-s** [comment]
> I am getting error on image picker in chat room.

@bitfriend  I used the same API and didn't face this kind of problem can you check again by reinstalling the app?

**Comment by bitfriend** [comment]
What is your env?

**Comment by sachintha-s** [comment]
> What is your env? And if possible, please share video that shows that action flow on your side.

I used an android API 23 emulator.


https://user-images.githubusercontent.com/65540448/194546332-ae726a56-3159-4e59-99cf-04326c863285.mp4

**Comment by sachintha-s** [comment]
@bitfriend Are you still facing this issue? otherwise, we can close this.

**Comment by bitfriend** [comment]
This is crash log in flutter 3.7.
```
D/FilePickerDelegate( 4496): Selected type image/*
E/Surface ( 4496): getSlotFromBufferLocked: unknown buffer: 0x7f95bc7271a0
D/EGL_emulation( 4496): eglMakeCurrent: 0x7f95c0136700: ver 2 0 (tinfo 0x7f95ad5e76e0)
E/Surface ( 4496): getSlotFromBufferLocked: unknown buffer: 0x7f95c0136a20
I/effektio-sdk( 4496): effektio::api::device: [2023-02-13][13:54:57][effektio::api::device][INFO] process device lists: SyncResponse { next_batch: "s57171_5719342_4864_147271_69790_73_73744_21647154_0_1", rooms: Rooms { leave: {}, join: {}, invite: {} }, presence: Presence { events: [] }, account_data: [], to_device_events: [], device_lists: DeviceLists { changed: [], left: [] }, device_one_time_keys_count: {}, ambiguity_changes: AmbiguityChanges { changes: {} }, notifications: {} }
I/FilePickerUtils( 4496): Caching from URI: content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Ffile%2F40/ORIGINAL/NONE/925836506
D/FilePickerUtils( 4496): File loaded and cached at:/data/user/0/org.effektio.app/cache/file_picker/IMG_20230213_215039.jpg
D/FilePickerDelegate( 4496): [MultiFilePick] File #0 - URI: /-1/1/content://media/external/file/40/ORIGINAL/NONE/925836506
E/EGL_emulation( 4496): tid 4514: init(361): error 0x3003 (EGL_BAD_ALLOC)
E/Surface ( 4496): getSlotFromBufferLocked: unknown buffer: 0x0
E/EGL_emulation( 4496): tid 4514: eglCreateWindowSurface(880): error 0x3003 (EGL_BAD_ALLOC)
E/EGL_emulation( 4496): tid 4514: eglMakeCurrent(1483): error 0x3009 (EGL_BAD_MATCH)
E/libEGL  ( 4496): eglMakeCurrent:809 error 3009 (EGL_BAD_MATCH)
E/flutter ( 4496): [ERROR:flutter/shell/platform/android/android_egl_surface.cc(234)] Could not make the context current
E/flutter ( 4496): [ERROR:flutter/shell/platform/android/android_egl_surface.cc(52)] EGL Error: EGL_BAD_MATCH (12297)
E/flutter ( 4496): [ERROR:flutter/shell/gpu/gpu_surface_gl_skia.cc(81)] Could not make the context current to set up the Gr context.
E/flutter ( 4496): [ERROR:flutter/shell/common/platform_view.cc(74)] Failed to create platform view rendering surface
E/libEGL  ( 4496): eglQuerySurface:624 error 300d (EGL_BAD_SURFACE)
E/flutter ( 4496): [ERROR:flutter/shell/platform/android/android_egl_surface.cc(276)] Unable to query EGL surface size
E/flutter ( 4496): [ERROR:flutter/shell/platform/android/android_egl_surface.cc(52)] EGL Error: EGL_BAD_SURFACE (12301)
E/libEGL  ( 4496): eglDestroySurface:595 error 300d (EGL_BAD_SURFACE)
E/EGL_emulation( 4496): tid 4514: init(361): error 0x3003 (EGL_BAD_ALLOC)
E/Surface ( 4496): getSlotFromBufferLocked: unknown buffer: 0x0
E/EGL_emulation( 4496): tid 4514: eglCreateWindowSurface(880): error 0x3003 (EGL_BAD_ALLOC)
E/flutter ( 4496): [ERROR:flutter/shell/platform/android/android_surface_gl_skia.cc(83)] Unable to create EGL window surface on resize.
E/EGL_emulation( 4496): tid 4526: init(361): error 0x3003 (EGL_BAD_ALLOC)
E/Surface ( 4496): getSlotFromBufferLocked: unknown buffer: 0x0
E/EGL_emulation( 4496): tid 4526: eglCreateWindowSurface(880): error 0x3003 (EGL_BAD_ALLOC)
F/OpenGLRenderer( 4496): Failed to create EGLSurface for window 0x7f95a7c0e210, eglErr = EGL_BAD_ALLOC
F/libc    ( 4496): Fatal signal 6 (SIGABRT), code -6 in tid 4526 (RenderThread)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Android/sdk_google_phone_x86_64/generic_x86_64:6.0/MASTER/6695544:userdebug/test-keys'
Revision: '0'
ABI: 'x86_64'
pid: 4496, tid: 4526, name: RenderThread  >>> org.effektio.app <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'Failed to create EGLSurface for window 0x7f95a7c0e210, eglErr = EGL_BAD_ALLOC'
    rax 0000000000000000  rbx 00007f95a8abf500  rcx ffffffffffffffff  rdx 0000000000000006
    rsi 00000000000011ae  rdi 0000000000001190
    r8  0000000000000012  r9  0000000000000003  r10 0000000000000008  r11 0000000000000206
    r12 00000000000011ae  r13 0000000000000006  r14 00007f95c5f2c070  r15 7fffffffffffffff
    cs  0000000000000033  ss  000000000000002b
    rip 00007f95c93eea67  rbp 0000000000000000  rsp 00007f95a8abec68  eflags 0000000000000206
backtrace:
    #00 pc 0000000000087a67  /system/lib64/libc.so (tgkill+7)
    #01 pc 0000000000085b11  /system/lib64/libc.so (pthread_kill+65)
    #02 pc 000000000002e841  /system/lib64/libc.so (raise+17)
    #03 pc 00000000000288fd  /system/lib64/libc.so (abort+61)
    #04 pc 000000000000dd84  /system/lib64/libcutils.so (__android_log_assert+212)
    #05 pc 000000000002cf8e  /system/lib64/libhwui.so
    #06 pc 00000000000281b2  /system/lib64/libhwui.so
    #07 pc 000000000002de1f  /system/lib64/libhwui.so
    #08 pc 000000000002dcda  /system/lib64/libhwui.so
    #09 pc 000000000002f62d  /system/lib64/libhwui.so
    #10 pc 0000000000031088  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+120)
    #11 pc 00000000000172f7  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+295)
    #12 pc 00000000000a3043  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+83)
    #13 pc 0000000000084eee  /system/lib64/libc.so (__pthread_start(void*)+46)
    #14 pc 00000000000296eb  /system/lib64/libc.so (__start_thread+11)
    #15 pc 000000000001ce55  /system/lib64/libc.so (__bionic_clone+53)
Tombstone written to: /data/tombstones/tombstone_03
Lost connection to device.
Exited (sigterm)
```

**Comment by bitfriend** [comment]
Fixed by https://github.com/effektio/effektio/pull/485
