### ISSUE TITLE
Rust build fails since latest PR

### ISSUE THREAD

**Issue by gnunicorn** [effektio/effektio#39]
doing `cargo make android`, comes back with:

```
   Compiling olm-sys v1.3.1
error: failed to run custom build command for `olm-sys v1.3.1`

Caused by:
  process didn't exit successfully: `/home/ben/Dev/effektio/effektio/target/debug/build/olm-sys-610c7a50f85f42f4/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'please set the ANDROID_NDK environment variable to your Android NDK instalation', /home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/olm-sys-1.3.1/build.rs:74:13
  stack backtrace:
     0:     0x5654248201ac - std::backtrace_rs::backtrace::libunwind::trace::hd70f18a67bf1064d
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x5654248201ac - std::backtrace_rs::backtrace::trace_unsynchronized::hed700f39aaa9560e
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x5654248201ac - std::sys_common::backtrace::_print_fmt::h05ffc8c800d3fd6e
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x5654248201ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc3335dc9ac9ea141
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x5654248434dc - core::fmt::write::h8ba7e47d56fb9287
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/core/src/fmt/mod.rs:1190:17
     5:     0x56542481b7e8 - std::io::Write::write_fmt::hcc4602e4a7d8cb4e
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/io/mod.rs:1657:15
     6:     0x565424822467 - std::sys_common::backtrace::_print::hfefb27db9027fc13
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x565424822467 - std::sys_common::backtrace::print::h3b5c5f5af201c47a
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x565424822467 - std::panicking::default_hook::{{closure}}::h9364b8e096329e42
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/panicking.rs:295:22
     9:     0x56542482211f - std::panicking::default_hook::hbb3fd2f25c08d7b9
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/panicking.rs:314:9
    10:     0x565424822bbb - std::panicking::rust_panic_with_hook::hb8806bff47a676e3
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/panicking.rs:698:17
    11:     0x5654247e90b8 - std::panicking::begin_panic::{{closure}}::h07522c056d581f2e
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/panicking.rs:617:9
    12:     0x5654247edcd9 - std::sys_common::backtrace::__rust_end_short_backtrace::ha0a40e4c96e98cfa
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/sys_common/backtrace.rs:138:18
    13:     0x5654247e904c - std::panicking::begin_panic::h6de11e247ba1a76f
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/panicking.rs:616:12
    14:     0x56542478ae75 - build_script_build::native_build::heea2a181a43f53eb
                                 at /home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/olm-sys-1.3.1/build.rs:74:13
    15:     0x56542478aa44 - build_script_build::main::h2f539368e30d2420
                                 at /home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/olm-sys-1.3.1/build.rs:47:9
    16:     0x565424790e7b - core::ops::function::FnOnce::call_once::hff972161059d8b9f
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/core/src/ops/function.rs:227:5
    17:     0x56542478d95e - std::sys_common::backtrace::__rust_begin_short_backtrace::hfe6f0b542aa24f4d
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/sys_common/backtrace.rs:122:18
    18:     0x56542478d641 - std::rt::lang_start::{{closure}}::h2b1e1751fbbac1c3
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/rt.rs:145:18
    19:     0x56542481f861 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h40514f9cff43fc7b
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/core/src/ops/function.rs:259:13
    20:     0x56542481f861 - std::panicking::try::do_call::h13c18fb0bf21b1ad
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/panicking.rs:492:40
    21:     0x56542481f861 - std::panicking::try::hc29ace249b5056de
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/panicking.rs:456:19
    22:     0x56542481f861 - std::panic::catch_unwind::h5fecb9a3411a9c08
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/panic.rs:137:14
    23:     0x56542481f861 - std::rt::lang_start_internal::{{closure}}::hde8de41944754fda
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/rt.rs:128:48
    24:     0x56542481f861 - std::panicking::try::do_call::h0fdf638f6d2f3c6e
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/panicking.rs:492:40
    25:     0x56542481f861 - std::panicking::try::h9c125cf762128efa
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/panicking.rs:456:19
    26:     0x56542481f861 - std::panic::catch_unwind::hacc18cc560a63b80
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/panic.rs:137:14
    27:     0x56542481f861 - std::rt::lang_start_internal::h649a40dabd53a16b
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/rt.rs:128:20
    28:     0x56542478d610 - std::rt::lang_start::h89418f3ee4ee3695
                                 at /rustc/68369a041cea809a87e5bd80701da90e0e0a4799/library/std/src/rt.rs:144:17
    29:     0x56542478c10c - main
    30:     0x7f0585f76310 - __libc_start_call_main
    31:     0x7f0585f763c1 - __libc_start_main@GLIBC_2.2.5
    32:     0x565424786c45 - _start
    33:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: build failed
[2022-03-10T15:13:43Z INFO  cargo_ndk::cli] If the build failed due to a missing target, you can run this command:
[2022-03-10T15:13:43Z INFO  cargo_ndk::cli] 
[2022-03-10T15:13:43Z INFO  cargo_ndk::cli]     rustup target install x86_64-linux-android
[cargo-make][1] ERROR - Error while executing command, exit code: 101
[cargo-make][1] WARN - Build Failed.
[cargo-make] ERROR - Error while running duckscript: Source: Unknown Line: 4 - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.
```

**Comment by gnunicorn** [comment]
I've fixed the CI and now it shows that error, too:

https://github.com/effektio/effektio/runs/5498129785?check_suite_focus=true#step:7:171

**Comment by gnunicorn** [comment]
@bmcpt yes, if you delete the lock file, it will fetch latest and that might be broken. But this now happens without deleting the lock file, meaning that the version we are locked to, is already broken.
