### ISSUE TITLE
Invalid argument(s): Failed to lookup symbol '__Room_latest_message': undefined symbol: __Room_latest_message

### ISSUE THREAD

**Issue by gtalha07** [effektio/effektio#55]
### Coming from ChatListItem in ChatOverview.dart
```
subtitle: FutureBuilder<RoomMessage>(
        future: room.latestMessage(),
        builder: (BuildContext context, snapshot) {
          if (snapshot.hasData) {
            return Container(
              margin: const EdgeInsets.only(top: 10),
              child: Text(
                '${snapshot.requireData.sender}',
                style: GoogleFonts.montserrat(
                  fontSize: 12,
                  color: Colors.white,
                ),
              ),
            );
          } else {
            return Container();
          }
        },
      ),
```
### Exceptions coming
```
Restarted application in 2,359ms.
I/flutter (28507): Restored [Instance of 'Client']: true
V/AudioManager(28507): playSoundEffect   effectType: 0
V/AudioManager(28507): querySoundEffectsEnabled...

════════ Exception caught by widgets library ═══════════════════════════════════
The following ArgumentError was thrown building ChatListItem(dirty):
Invalid argument(s): Failed to lookup symbol '__Room_latest_message': undefined symbol: __Room_latest_message

The relevant error-causing widget was
ChatListItem
When the exception was thrown, this was the stack
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:34:70)
#1      Api._roomLatestMessagePtr
#2      Api._roomLatestMessagePtr (package:effektio_flutter_sdk/effektio_flutter_sdk_ffi.dart)
#3      Api._roomLatestMessage
#4      Api._roomLatestMessage (package:effektio_flutter_sdk/effektio_flutter_sdk_ffi.dart)
#5      Room.latestMessage
#6      ChatListItem.build
#7      StatelessElement.build
#8      ComponentElement.performRebuild
#9      Element.rebuild
#10     ComponentElement._firstBuild
#11     ComponentElement.mount
#12     Element.inflateWidget
#13     MultiChildRenderObjectElement.inflateWidget
#14     MultiChildRenderObjectElement.mount
...     Normal element mounting (33 frames)
#47     Element.inflateWidget
#48     Element.updateChild
#49     SliverMultiBoxAdaptorElement.updateChild
#50     SliverMultiBoxAdaptorElement.createChild.<anonymous closure>
#51     BuildOwner.buildScope
#52     SliverMultiBoxAdaptorElement.createChild
#53     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>
#54     RenderObject.invokeLayoutCallback.<anonymous closure>
#55     PipelineOwner._enableMutationsToDirtySubtrees
#56     RenderObject.invokeLayoutCallback
#57     RenderSliverMultiBoxAdaptor._createOrObtainChild
#58     RenderSliverMultiBoxAdaptor.addInitialChild
#59     RenderSliverList.performLayout
#60     RenderObject.layout
#61     RenderSliverEdgeInsetsPadding.performLayout
#62     RenderSliverPadding.performLayout
#63     RenderObject.layout
#64     RenderViewportBase.layoutChildSequence
#65     RenderShrinkWrappingViewport._attemptLayout
#66     RenderShrinkWrappingViewport.performLayout
#67     RenderObject.layout
#68     RenderProxyBoxMixin.performLayout
#69     RenderObject.layout
#70     RenderProxyBoxMixin.performLayout
#71     RenderObject.layout
#72     RenderProxyBoxMixin.performLayout
#73     RenderObject.layout
#74     RenderProxyBoxMixin.performLayout
#75     RenderObject.layout
#76     RenderProxyBoxMixin.performLayout
#77     RenderObject.layout
#78     RenderProxyBoxMixin.performLayout
#79     RenderObject.layout
#80     RenderProxyBoxMixin.performLayout
#81     RenderObject.layout
#82     RenderProxyBoxMixin.performLayout
#83     RenderCustomPaint.performLayout
#84     RenderObject.layout
#85     RenderProxyBoxMixin.performLayout
#86     RenderObject.layout
#87     ChildLayoutHelper.layoutChild
#88     RenderFlex._computeSizes
#89     RenderFlex.performLayout
#90     RenderObject.layout
#91     MultiChildLayoutDelegate.layoutChild
#92     _ScaffoldLayout.performLayout
#93     MultiChildLayoutDelegate._callPerformLayout
#94     RenderCustomMultiChildLayoutBox.performLayout
#95     RenderObject.layout
#96     RenderProxyBoxMixin.performLayout
#97     RenderObject.layout
#98     RenderProxyBoxMixin.performLayout
#99     _RenderCustomClip.performLayout
#100    RenderObject.layout
#101    MultiChildLayoutDelegate.layoutChild
#102    _ScaffoldLayout.performLayout
#103    MultiChildLayoutDelegate._callPerformLayout
#104    RenderCustomMultiChildLayoutBox.performLayout
#105    RenderObject._layoutWithoutResize
#106    PipelineOwner.flushLayout
#107    RendererBinding.drawFrame
#108    WidgetsBinding.drawFrame
#109    RendererBinding._handlePersistentFrameCallback
#110    SchedulerBinding._invokeFrameCallback
#111    SchedulerBinding.handleDrawFrame
#112    SchedulerBinding._handleDrawFrame
#116    _invoke (dart:ui/hooks.dart:151:10)
#117    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#118    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Invalid argument(s): Failed to lookup symbol '__Room_latest_message': undefined symbol: __Room_latest_message
The relevant error-causing widget was
ChatListItem
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Invalid argument(s): Failed to lookup symbol '__Room_latest_message': undefined symbol: __Room_latest_message
The relevant error-causing widget was
ChatListItem
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Invalid argument(s): Failed to lookup symbol '__Room_latest_message': undefined symbol: __Room_latest_message
The relevant error-causing widget was
ChatListItem
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Invalid argument(s): Failed to lookup symbol '__Room_latest_message': undefined symbol: __Room_latest_message
The relevant error-causing widget was
ChatListItem
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Invalid argument(s): Failed to lookup symbol '__Room_latest_message': undefined symbol: __Room_latest_message
The relevant error-causing widget was
ChatListItem
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 599417 pixels on the bottom.
The relevant error-causing widget was
Column
════════════════════════════════════════════════════════════════════════════════
E/flutter (28507): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: No avatar
E/flutter (28507):
I/chatty  (28507): uid=10173(com.example.effektio) 1.ui identical 1 line
E/flutter (28507): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: No avatar
E/flutter (28507):
E/flutter (28507): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: No avatar
E/flutter (28507):
```

**Comment by gtalha07** [comment]
I did run 'cargo make android' before starting application but the issue still persists. @gnunicorn 
This seems similar to #10

**Comment by gtalha07** [comment]
something magical happened and its gone for now.
